# BasicCAD

We are creating a caster.

---
## Table of Contents
* [Table of Contents](#Table-of-Contents)
* [Base](#Base)
* [Mount](#Mount)
* [Fork](#Fork)
* [Tire](#Tire)
* [Wheel](#Wheel)
* [AxleCollarBearings](#AxleCollarBearings)

## Base

### Description

The first assignment is to create the caster base.  The base's dimensions are 200 mm x 120 mm and 8 mm thick.  It has 6 holes 10 mm wide and 20 mm from the edge equally spaced along the edges.

### Evidence
[The Base in Onshape](https://cvilleschools.onshape.com/documents/0d70f655203ca304cb3c5b7d/w/f55603f962f6fc74f5548a68/e/41d730c570a8d75fce9f51b6)

### Image
This is how you will write image code for INTERNALLY STORED images on your repo.   just FYI.
~~~
<img src="images/Base.jpg" alt="The Base" width="200">
~~~
<img src="https://github.com/OneCHSEngr/BasicCAD/blob/master/images/Base.jpg" width="400">

### Reflection

This was my first Onshape part and [following along with Dr. Shields made it super easy.](https://www.youtube.com/watch?v=93BFUD-HAG8&feature=emb_title&scrlybrkr=5670f0b4)  I learned about 
* sketching (shortcut **shift-s**)
* constructions lines (shortcut **Q**)
* dimensions (shortcut **D**)
* extruding both add and remove (shortcut key **E**)
* linear patterns (no shortcut)

Onshape is awesome.  I found it really helpful to rename all my sketches.  It is going to be a GREAT year in engineering.

---


## Mount

### Description
This will be the mount that attaches on top of the base. It's a 120mm x 120mm square that has 4 symmetrical holes in the corners which are 10mm in diameter and 20mm away from each side and there's also one hole in the center of the square that's 25mm in diameter.
### Evidence
[This will be the base and the mount together](https://cvilleschools.onshape.com/documents/479715e6894280b7f139703f/w/20b45e11a4abc891c7df0507/e/788c47b60e10c326a212102b)
### Image
<img src="https://github.com/Adicesa05/Images/blob/main/Mount.png" width="400">

### Reflection
An easier and faster way to build the mount is by drawing a verticle line on the base to make a 120mm x 120mm square and using the Use Tool and selecting the parts to extrude, after that extrude the part by 8mm selecting "new" so the part is separate from the base.

---


## Fork

### Description
This will be the fork it is attacted to the axle and it is used to rotate the wheel. The arm is 15mm away from the origin and has holes on both sides for the axle to go through. The end will be used to attach to the caster base.
### Evidence
[This will be the fork](https://cvilleschools.onshape.com/documents/59af1eb863a6936014b48452/w/9e151c8707c5dfc4d2ebde74/e/aa741dacae40c24785d1d18a)
### Image
<img src="https://github.com/Adicesa05/Images/blob/main/Fork.png" width="400">

### Reflection
Make sure to mirror feature or you will have 2 bases inside of each other
You can move a sketch that you may have made before an extrude to the surface of the extrude by dragging your sketch in the features to be below the extrude.

---


## Tire

### Description
The tire will be attached on the wheel with an inner radius of 80mm and outer radius of 110mm.
### Evidence
[The tire will be in the same document as the wheel but different parts](https://cvilleschools.onshape.com/documents/a619828fb00e7c97e003d335/w/d594064e5640e8c8940c262d/e/9d9fd4e8bd0667ffbbad85e7)
### Image
<img src="https://github.com/Adicesa05/Images/blob/main/Tire.png" width="400">

### Reflection
Make sure the two edges on the trapezoid are symmetrical and to use revolve instead of extrude.

---


## Wheel

### Description
The tire will be the part that holds the axle in the center hole. The radius of the wheel is 80mm.
### Evidence
[The tire will be in the same document as the wheel but different parts](https://cvilleschools.onshape.com/documents/a619828fb00e7c97e003d335/w/d594064e5640e8c8940c262d/e/9d9fd4e8bd0667ffbbad85e7)
### Image
<img src="https://github.com/Adicesa05/Images/blob/main/Wheel.png" width="400">

### Reflection
Make sure the outer edges on the sketch is symmetric to the middle line from the origin.
For the sketch of the 5 holes of the wheel you can draw two lines from the origin and make them 60degrees apart and draw a three point arc from there.

---


## AxleCollarBearings

### Description
These are the parts that will attach together and will go in the wheel.
### Evidence
[This will be the Axel, Collar and Bearings together](https://cvilleschools.onshape.com/documents/74c370696eeb7452f7d4c420/w/d904ad10829b73d5445f0911/e/5c862463e963d4c7f83e0215)
### Image
<img src="https://github.com/Adicesa05/Images/blob/main/Axel%2C%20Collar%2C%20Bearing.png" width="400">

### Reflection
When you want to sketch on a specific part use the "use tool".


---
